services:
  node_server:
    build: ..
    container_name: node_server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /etc/ssl/cloudflare:/etc/ssl/cloudflare:ro
    environment:
      NODE_ENV: production